export const categoryListObject = {
  Aperitivos: "Aperitivos",
  Tapas: "Tapas",
  Arroces: "Arroces",
  Cereales: "Cereales",
  Aves: "Aves",
  Carne: "Carne",
  Cócteles: "Cócteles",
  Bebidas: "Bebidas",
  Ensaladas: "Ensaladas",
  Guisos: "Guisos",
  Huevos: "Huevos",
  Lácteos: "Lácteos",
  Legumbres: "Legumbres",
  Mariscos: "Mariscos",
  Pan: "Pan",
  Bollería: "Bollería",
  Pasta: "Pasta",
  Pescado: "Pescado",
  Postres: "Postres",
  Salsas: "Salsas",
  Sopas: "Sopas",
  Cremas: "Cremas",
  Verduras: "Verduras",
};

export const categoryList = [
  "Aperitivos",
  "Tapas",
  "Arroces",
  "Cereales",
  "Aves",
  "Carne",
  "Cócteles",
  "Bebidas",
  "Ensaladas",
  "Guisos",
  "Huevos",
  "Lácteos",
  "Legumbres",
  "Mariscos",
  "Pan",
  "Bollería",
  "Pasta",
  "Pescado",
  "Postres",
  "Salsas",
  "Sopas",
  "Cremas",
  "Verduras",
];
